module.exports = {
    name: 'leicester-end',
    meta: {
        name: 'Mice on the line',
        key: 'leicester-end',
        length: 10,
        description: 'a story',
    },
    clips: [{
        type: 'name',
        number: 1,
    }, {
        type: 'main',
        number: 1,
        adelay: 50,
    }, {
        type: 'main',
        number: 2,
    }, {
        type: 'main',
        number: 3,
    }, {
        type: 'main',
        number: 4,
        adelay: 350,
    }, {
        type: 'npc',
        npcNumber: 1,
        number: 1,
        adelay: 200,
    }, {
        type: 'main',
        number: 5,
    }, {
        type: 'main',
        number: 6,
    }, {
        type: 'main',
        number: 7,
        adelay: 200,
    }, {
        type: 'name',
        number: 5,
    }, {
        type: 'main',
        number: 8,
    }, {
        type: 'npc',
        npcNumber: 1,
        number: 1,
        adelay: 200,
    }, {
        type: 'main',
        number: 9,
    }, {
        type: 'main',
        number: 10,
    }, {
        type: 'main',
        number: 11,
        adelay: 200,
    }, {
        type: 'npc',
        npcNumber: 0,
        number: 1
    }, {
        type: 'main',
        number: 12,
    }, {
        type: 'name',
        number: 1,
        adelay: 100,
    }, {
        type: 'main',
        number: 13,
    }, {
        type: 'main',
        number: 14,
    }, ]
}